-- SQL query to create the chronobreak database, cities table, and insert cities data into MySQL database

CREATE DATABASE IF NOT EXISTS chronobreak;
USE chronobreak;

CREATE TABLE IF NOT EXISTS cities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  country_code VARCHAR(2) NOT NULL,
  country_name VARCHAR(255) NOT NULL,
  capital_city VARCHAR(255) NOT NULL
);

INSERT INTO cities (country_code, country_name, capital_city) VALUES
('AD', 'Andorra', 'Andorra la Vella'),
('AE', 'United Arab Emirates', 'Abu Dhabi'),
('AF', 'Afghanistan', 'Kabul'),
('AG', 'Antigua and Barbuda', 'Saint Johns'),
('AI', 'Anguilla', 'The Valley'),
('AL', 'Albania', 'Tirana'),
('AM', 'Armenia', 'Yerevan'),
('AO', 'Angola', 'Luanda'),
('AQ', 'Antarctica', 'N/A'),
('TH','Thailand', 'Bangkok'),
('AR', 'Argentina', 'Buenos Aires'),
('AS', 'American Samoa', 'Pago Pago'),
('AT', 'Austria', 'Vienna'),
('AU', 'Australia', 'Canberra'),
('AW', 'Aruba', 'Oranjestad'),
('AX', 'Åland Islands', 'Mariehamn'),
('AZ', 'Azerbaijan', 'Baku'),
('BA', 'Bosnia and Herzegovina', 'Sarajevo'),
('BB', 'Barbados', 'Bridgetown'),
('BD', 'Bangladesh', 'Dhaka'),
('BE', 'Belgium', 'Brussels'),
('BF', 'Burkina Faso', 'Ouagadougou'),
('BG', 'Bulgaria', 'Sofia'),
('BH', 'Bahrain', 'Manama'),
('BI', 'Burundi', 'Gitega'),
('BJ', 'Benin', 'Porto-Novo'),
('BL', 'Saint Barthélemy', 'Gustavia'),
('BM', 'Bermuda', 'Hamilton'),
('BN', 'Brunei', 'Bandar Seri Begawan'),
('BO', 'Bolivia', 'Sucre'),
('BQ', 'Bonaire', 'Kralendijk'),
('BR', 'Brazil', 'Brasília'),
('BS', 'Bahamas', 'Nassau'),
('BT', 'Bhutan', 'Thimphu'),
('BW', 'Botswana', 'Gaborone'),
('BY', 'Belarus', 'Minsk'),
('BZ', 'Belize', 'Belmopan'),
('CA', 'Canada', 'Ottawa'),
('CC', 'Cocos (Keeling) Islands', 'West Island'),
('CD', 'Congo (Kinshasa)', 'Kinshasa'),
('CF', 'Central African Republic', 'Bangui'),
('CG', 'Congo (Brazzaville)', 'Brazzaville'),
('CH', 'Switzerland', 'Bern'),
('CI', 'Côte d\Ivoire', 'Yamoussoukro'),
('CK', 'Cook Islands', 'Avarua'),
('CL', 'Chile', 'Santiago'),
('CM', 'Cameroon', 'Yaoundé'),
('CN', 'China', 'Beijing'),
('CO', 'Colombia', 'Bogotá'),
('CR', 'Costa Rica', 'San José'),
('CU', 'Cuba', 'Havana'),
('CV', 'Cape Verde', 'Praia'),
('CW', 'Curaçao', 'Willemstad'),
('CX', 'Christmas Island', 'Flying Fish Cove'),
('CY', 'Cyprus', 'Nicosia'),
('CZ', 'Czech Republic', 'Prague'),
('DE', 'Germany', 'Berlin'),
('DJ', 'Djibouti', 'Djibouti'),
('DK', 'Denmark', 'Copenhagen'),
('DM', 'Dominica', 'Roseau'),
('DO', 'Dominican Republic', 'Santo Domingo'),
('DZ', 'Algeria', 'Algiers'),
('EC', 'Ecuador', 'Quito'),
('EE', 'Estonia', 'Tallinn'),
('EG', 'Egypt', 'Cairo'),
('EH', 'Western Sahara', 'El Aaiún'),
('ER', 'Eritrea', 'Asmara'),
('ES', 'Spain', 'Madrid'),
('ET', 'Ethiopia', 'Addis Ababa'),
('FI', 'Finland', 'Helsinki'),
('FJ', 'Fiji', 'Suva'),
('FK', 'Falkland Islands', 'Stanley'),
('FM', 'Micronesia', 'Palikir'),
('FO', 'Faroe Islands', 'Tórshavn'),
('FR', 'France', 'Paris'),
('GA', 'Gabon', 'Libreville'),
('GB', 'United Kingdom', 'London'),
('GD', 'Grenada', 'St. George\s'),
('GE', 'Georgia', 'Tbilisi'),
('GF', 'French Guiana', 'Cayenne'),
('GG', 'Guernsey', 'St. Peter Port'),
('GH', 'Ghana', 'Accra'),
('GI', 'Gibraltar', 'Gibraltar'),
('GL', 'Greenland', 'Nuuk'),
('GM', 'Gambia', 'Banjul'),
('GN', 'Guinea', 'Conakry'),
('GP', 'Guadeloupe', 'Basse-Terre'),
('GQ', 'Equatorial Guinea', 'Malabo'),
('GR', 'Greece', 'Athens'),
('GS', 'South Georgia and the South Sandwich Islands', 'King Edward Point'),
('GT', 'Guatemala', 'Guatemala City'),
('GU', 'Guam', 'Hagåtña'),
('GW', 'Guinea-Bissau', 'Bissau'),
('GY', 'Guyana', 'Georgetown'),
('HK', 'Hong Kong', 'Hong Kong'),
('HN', 'Honduras', 'Tegucigalpa'),
('HR', 'Croatia', 'Zagreb'),
('HT', 'Haiti', 'Port-au-Prince'),
('HU', 'Hungary', 'Budapest'),
('ID', 'Indonesia', 'Jakarta'),
('IE', 'Ireland', 'Dublin'),
('IL', 'Israel', 'Jerusalem'),
('IM', 'Isle of Man', 'Douglas'),
('IN', 'India', 'New Delhi'),
('IO', 'British Indian Ocean Territory', 'Diego Garcia'),
('IQ', 'Iraq', 'Baghdad'),
('IR', 'Iran', 'Tehran'),
('IS', 'Iceland', 'Reykjavik'),
('IT', 'Italy', 'Rome'),
('JE', 'Jersey', 'Saint Helier'),
('JM', 'Jamaica', 'Kingston'),
('JO', 'Jordan', 'Amman'),
('JP', 'Japan', 'Tokyo'),
('KE', 'Kenya', 'Nairobi'),
('KG', 'Kyrgyzstan', 'Bishkek'),
('KH', 'Cambodia', 'Phnom Penh'),
('KI', 'Kiribati', 'Tarawa'),
('KM', 'Comoros', 'Moroni'),
('KN', 'Saint Kitts and Nevis', 'Basseterre'),
('KP', 'North Korea', 'Pyongyang'),
('KR', 'South Korea', 'Seoul'),
('KW', 'Kuwait', 'Kuwait City'),
('KY', 'Cayman Islands', 'George Town'),
('KZ', 'Kazakhstan', 'Nur-Sultan'),
('LA', 'Laos', 'Vientiane'),
('LB', 'Lebanon', 'Beirut'),
('LC', 'Saint Lucia', 'Castries'),
('LI', 'Liechtenstein', 'Vaduz'),
('LK', 'Sri Lanka', 'Sri Jayawardenepura Kotte'),
('LR', 'Liberia', 'Monrovia'),
('LS', 'Lesotho', 'Maseru'),
('LT', 'Lithuania', 'Vilnius'),
('LU', 'Luxembourg', 'Luxembourg'),
('LV', 'Latvia', 'Riga'),
('LY', 'Libya', 'Tripoli'),
('MA', 'Morocco', 'Rabat'),
('MC', 'Monaco', 'Monaco'),
('MD', 'Moldova', 'Chișinău'),
('ME', 'Montenegro', 'Podgorica'),
('MF', 'Saint Martin', 'Marigot'),
('MG', 'Madagascar', 'Antananarivo'),
('MH', 'Marshall Islands', 'Majuro'),
('MK', 'North Macedonia', 'Skopje'),
('ML', 'Mali', 'Bamako'),
('MM', 'Myanmar', 'Naypyidaw'),
('MN', 'Mongolia', 'Ulaanbaatar'),
('MO', 'Macau', 'Macau'),
('MP', 'Northern Mariana Islands', 'Saipan'),
('MQ', 'Martinique', 'Fort-de-France'),
('MR', 'Mauritania', 'Nouakchott'),
('MS', 'Montserrat', 'Plymouth'),
('MT', 'Malta', 'Valletta'),
('MU', 'Mauritius', 'Port Louis'),
('MV', 'Maldives', 'Malé'),
('MW', 'Malawi', 'Lilongwe'),
('MX', 'Mexico', 'Mexico City'),
('MY', 'Malaysia', 'Kuala Lumpur'),
('MZ', 'Mozambique', 'Maputo'),
('NA', 'Namibia', 'Windhoek'),
('NC', 'New Caledonia', 'Nouméa'),
('NE', 'Niger', 'Niamey'),
('NF', 'Norfolk Island', 'Kingston'),
('NG', 'Nigeria', 'Abuja'),
('NI', 'Nicaragua', 'Managua'),
('NL', 'Netherlands', 'Amsterdam'),
('NO', 'Norway', 'Oslo'),
('NP', 'Nepal', 'Kathmandu'),
('NR', 'Nauru', 'Yaren'),
('NU', 'Niue', 'Alofi'),
('NZ', 'New Zealand', 'Wellington'),
('OM', 'Oman', 'Muscat'),
('PA', 'Panama', 'Panama City'),
('PE', 'Peru', 'Lima'),
('PF', 'French Polynesia', 'Papeete'),
('PG', 'Papua New Guinea', 'Port Moresby'),
('PH', 'Philippines', 'Manila'),
('PK', 'Pakistan', 'Islamabad'),
('PL', 'Poland', 'Warsaw'),
('PM', 'Saint Pierre and Miquelon', 'Saint-Pierre'),
('PN', 'Pitcairn Islands', 'Adamstown'),
('PR', 'Puerto Rico', 'San Juan'),
('PS', 'Palestine', 'Ramallah'),
('PT', 'Portugal', 'Lisbon'),
('PW', 'Palau', 'Ngerulmud'),
('PY', 'Paraguay', 'Asunción'),
('QA', 'Qatar', 'Doha'),
('RE', 'Réunion', 'Saint-Denis'),
('RO', 'Romania', 'Bucharest'),
('RS', 'Serbia', 'Belgrade'),
('RU', 'Russia', 'Moscow'),
('RW', 'Rwanda', 'Kigali'),
('SA', 'Saudi Arabia', 'Riyadh'),
('SB', 'Solomon Islands', 'Honiara'),
('SC', 'Seychelles', 'Victoria'),
('SD', 'Sudan', 'Khartoum'),
('SE', 'Sweden', 'Stockholm'),
('SG', 'Singapore', 'Singapore'),
('SH', 'Saint Helena', 'Jamestown'),
('SI', 'Slovenia', 'Ljubljana'),
('SJ', 'Svalbard and Jan Mayen', 'Longyearbyen'),
('SK', 'Slovakia', 'Bratislava'),
('SL', 'Sierra Leone', 'Freetown'),
('SM', 'San Marino', 'San Marino'),
('SN', 'Senegal', 'Dakar'),
('SO', 'Somalia', 'Mogadishu'),
('SR', 'Suriname', 'Paramaribo'),
('SS', 'South Sudan', 'Juba'),
('ST', 'São Tomé and Príncipe', 'São Tomé'),
('SV', 'El Salvador', 'San Salvador'),
('SX', 'Sint Maarten', 'Philipsburg'),
('SY', 'Syria', 'Damascus'),
('SZ', 'Eswatini', 'Mbabane'),
('TC', 'Turks and Caicos Islands', 'Cockburn Town'),
('TD', 'Chad', 'N\Djamena'),
('TF', 'French Southern Territories', 'Port-aux-Français'),
('TG', 'Togo', 'Lomé'),
('TH', 'Thailand', 'Bangkok'),
('TJ', 'Tajikistan', 'Dushanbe'),
('TK', 'Tokelau', 'Nukunonu'),
('TL', 'Timor-Leste', 'Dili'),
('TM', 'Turkmenistan', 'Ashgabat'),
('TN', 'Tunisia', 'Tunis'),
('TO', 'Tonga', 'Nuku alofa'),
('TR', 'Turkey', 'Ankara'),
('TT', 'Trinidad and Tobago', 'Port of Spain'),
('TV', 'Tuvalu', 'Funafuti'),
('TW', 'Taiwan', 'Taipei'),
('TZ', 'Tanzania', 'Dodoma'),
('UA', 'Ukraine', 'Kyiv'),
('UG', 'Uganda', 'Kampala'),
('UM', 'United States Minor Outlying Islands', 'N/A'),
('US', 'United States', 'Washington, D.C.'),
('UY', 'Uruguay', 'Montevideo'),
('UZ', 'Uzbekistan', 'Tashkent'),
('VA', 'Vatican City', 'Vatican City'),
('VC', 'Saint Vincent and the Grenadines', 'Kingstown'),
('VE', 'Venezuela', 'Caracas'),
('VG', 'British Virgin Islands', 'Road Town'),
('VI', 'U.S. Virgin Islands', 'Charlotte Amalie'),
('VN', 'Vietnam', 'Hanoi'),
('VU', 'Vanuatu', 'Port Vila'),
('WF', 'Wallis and Futuna', 'Mata-Utu'),
('WS', 'Samoa', 'Apia'),
('YE', 'Yemen', 'Sana'),
('YT', 'Mayotte', 'Mamoudzou'),
('ZA', 'South Africa', 'Pretoria'),
('ZM', 'Zambia', 'Lusaka'),
('ZW', 'Zimbabwe', 'Harare');